
var questions = [
    new Question("What is the capital city of the United Kingdom?", "London", "Manchester", "Liverpool","Reding"), 
    new Question("How tall is Mount Everest?", "8848m", "9848m", "4484m", "8488m"),
    new Question("What continent is Turkey on?", "Asia", "Australia", "Europe", "Russia"),
    new Question("How long is the river Nile?", "6650km", "5650km", "3690km", "4800km"),
    new Question("What country is on the continent of Africa?", "Kenya", "Jordan", "Bhutan", "Nepal"),
    new Question("What is the mountain range that goes trough the North of Italy?", "Alps", "Carpathians", "Urals", "Caucasus"),
    new Question("What is the name of the peninsula where Sweden is located?", "Scandinavian", "Arabian", "Iberian", "Balkan"),
    new Question("What is the largest country in the world?", "Russia", "China", "Canada", "United States"),
    new Question("Out of all the countries listed, which one have the largest population?", "Germany", "United Kingdom", "France", "Romania"),
    new Question("What is the capital of Moldova?", "Chisinau", "Balti", "Iasi", "Piatra Neamt"),
    new Question("What is the largest city in Europe?", "Istanbul", "London", "Moscow", "Paris"),
    new Question("What country has the Danube Delta on its territory?", "Romania", "Denmark", "Hungary", "Germany"),
    new Question("What is the capital city of China?", "Beijing", "Hong Kong", "Shanghai", "Shenzen"),
    new Question("What is the tallest mountain on the United States of America territory?", "Denali", "Mount Bona", "Mount Sanford", "Mount Saint Elias"),
    new Question("What is the longest river in Europe?", "Volga", "Danube", "Ural", "Don"),
    new Question("What is the most populous country in the world?", "China", "India", "United States", "Indonesia"),
    new Question("Which country has the most islands in Europe?", "Finland", "Greece", "Italy", "France"),
    new Question("What is the worlds largest lake in volume?", "Baikal", "Great Bear Lake", "Michigan", "Tanganyika"),
    new Question("What is the world's largest vulcano?", "Mauna Loa", "Vesuvius", "Sakurajima", "Galeras"),
    new Question("What is the highest mountain in Britain?", "Ben Nevis", "Mangerton", "Purple Mountain", "The Cheviot"),
    new Question("What country has the longest coastline in the world??", "Canada", "China", "Russia", "United States"),
    new Question("What country is Beirut the capital of?", "Lebanon", "Armenia", "Azerbaijan", "Kazakhstan"),
    new Question("The southern tip of South America has what name?", "Aguila Islet", "Punta Gallinas", "Brasil", "Aconcagua"),
];
var score = 0;
var j = parseInt(Math.random() * questions.length);

var askedQuestions = [];
var pickedJ = [];
var allNumbers = [];


function Question(quest, rightAnswer, falseAnswer1, falseAnswer2, falseAnswer3){
    this.quest = quest;
    this.rightAnswer = rightAnswer;
    this.falseAnswer1 = falseAnswer1;
    this.falseAnswer2 = falseAnswer2;
    this.falseAnswer3 = falseAnswer3;
}

function startGame(){
    getQuestion(j);
    document.getElementById('startBox').classList.add('hide');
    document.getElementById('gameOver-box').classList.add('hide');
    document.getElementById('questionBox').classList.remove('hide');
}
function randomizeAnswer(i){
    /*this function randomises the answers from the question object by using 2 arrays, one for the answers and one for the random index generated by the conditions I've put in the functions which are supposed to keep the numbers from repeating themselves in the array*/
    var buttonAnswers = [questions[i].rightAnswer, questions[i].falseAnswer1, questions[i].falseAnswer2, questions[i].falseAnswer3];
    var randomNumbers = [];
    randomNumbers[0] = parseInt(Math.random() * 4);
    var randomNum = parseInt(Math.random() * 4);

    console.log(askedQuestions);

    if(randomNumbers.includes(randomNum)){
        while(randomNumbers.includes(randomNum)){
            randomNum = parseInt(Math.random() * 4);
        }
        randomNumbers[1] = randomNum; 
        
    }else{
        randomNumbers[1] = randomNum;  
        }

    if(randomNumbers.includes(randomNum)){
        while(randomNumbers.includes(randomNum)){
            randomNum = parseInt(Math.random() * 4);
        }
        randomNumbers[2] = randomNum; 
        
    }else{
        randomNumbers[2] = randomNum;  
        }

    if(randomNumbers.includes(randomNum)){
        while(randomNumbers.includes(randomNum)){
            randomNum = parseInt(Math.random() * 4);
        }
        randomNumbers[3] = randomNum; 
        
    }else{
        randomNumbers[3] = randomNum;  
        }
    document.getElementById("answer1").value=buttonAnswers[randomNumbers[0]];
    document.getElementById("answer2").value=buttonAnswers[randomNumbers[1]];
    document.getElementById("answer3").value=buttonAnswers[randomNumbers[2]];
    document.getElementById("answer4").value=buttonAnswers[randomNumbers[3]];
    
} 

function getQuestion(j){
    document.getElementById("scoreText").innerHTML ="Score: " + score;
    var buttons = document.getElementsByClassName("answerbutton"); 
    for(var i = 0; i<buttons.length; i++){
        buttons[i].addEventListener("click", whenButtonClicked);
        console.log("adding stuff");
        }
        if(askedQuestions.includes(questions[j])){
            console.log(j);
            while(askedQuestions.includes(questions[j])){
                j = parseInt(Math.random() * questions.length);
                console.log(questions[j]);
                console.log(j);
            }
            document.getElementById("question").innerHTML = questions[j].quest;
            randomizeAnswer(j);
            askedQuestions.push(questions[j]);
            pickedJ.push(j);
        }else{
        document.getElementById("question").innerHTML = questions[j].quest;
        randomizeAnswer(j);
        askedQuestions.push(questions[j]);
        pickedJ.push(j);
        console.log(j);
        
    } 
}


function whenButtonClicked(){
    console.log("Length of array askedQuestions: " + askedQuestions.length);

     if(document.getElementById(this.id).value===askedQuestions[askedQuestions.length - 1].rightAnswer){
        if(askedQuestions.length == 20){
            console.log("length is equal to 20");
            score++;
            playAgain();
        }else{
        score++;
        getQuestion(j);
        }
    }else{
        if(askedQuestions.length == 20){
            console.log("length is equal to 20");
            playAgain();
        }else{
        getQuestion(j);
        }
    }
}


function playAgain(){
    document.getElementById('questionBox').classList.add('hide');
    document.getElementById('gameOver-box').classList.remove('hide');
    document.getElementById('scorePromt').innerHTML = "You have answered correctly " + score + "/20 questions!";
    
}